### ISSUE TITLE
Incoherence size indicated and size provided in forward of Sequential Model

### ISSUE THREAD

**Issue by nathanb97** [cristinalunaj/MMEmotionRecognition#5]
Hello,
First of all, thank you for your excellent paper, very pleasant to read, and your code too.
It's quite rare to have a clear enough code with a good paper 

However there are some small errors in your code that prevent me from trying yours models. 

For the Facial Emotion Recognition
For the sequential model for Video/models/sequenceLearning/workflow/run.py
Following the MMEmotionRecognition/src/Video/models/sequenceLearning/README_AUS.md

The error that prevents me from continuing to continue is the following: 
```
    raise RuntimeError(
RuntimeError: input.size(-1) must be equal to input_size. Expected 35, got 714
```
In  forward of LSTMEncoder()

Indeed a csv has 714 columns, did you select all of them ?

Because in your config file You had indicated 35 in input_size.
Thank you for your answer.

**Comment by cristinalunaj** [comment]
Hello, thanks for your comments :) 
I think that the error is because the model is expecting 35 columns, that should be the 35 AUs extracted from OpenFace (all the AUXX_c and AUXX_r) after running the python file [AUsFeatureExtractor.py](https://github.com/cristinalunaj/MMEmotionRecognition/blob/main/src/Video/OpenFace/AUsFeatureExtractor.py), i didn't include it in the tutorial of the sequenceLearning, but it is in the main README under Facial Emotion Recognition. 
Sorry for the inconvenience.

**Comment by nathanb97** [comment]
Hello Cristina,
No problem.
Thank you very much for the reply.
I close the issue.
